### ISSUE TITLE
Tray doesn't lift when there are cubes

### ISSUE THREAD

**Issue by nashirj** [smcrobotics/VEX_U_Competition_Design#4]
Add second motor to tray lift mechanism

**Comment by nashirj** [comment]
Note that tray also does not move when there are no cubes, it can't raise at all with the double tray. If the starting angle is larger, i.e. the tray is closer to being perpendicular with the ground, the tray lifting mechanism works.

**Comment by jeiook** [comment]
After some structural changes, we are able to lift the tray with the cubes on them. We may not need to make drastic changes.
